import { Task, User, PomodoroSession, CalendarEvent, Notification } from '../types';

// Mock User Data
export const mockUser: User = {
  id: '1',
  email: 'john.doe@example.com',
  name: 'John Doe',
  avatar: 'https://via.placeholder.com/150',
  createdAt: new Date('2024-01-01T00:00:00Z'),
  updatedAt: new Date('2024-01-15T10:30:00Z'),
};

// Mock Tasks Data
export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Complete project proposal',
    description: 'Write a comprehensive project proposal for the new AI scheduler feature',
    priority: 'high',
    status: 'in_progress',
    dueDate: new Date('2024-01-20T17:00:00Z'),
    estimatedDuration: 120,
    actualDuration: 45,
    aiGenerated: false,
    tags: ['work', 'proposal', 'ai'],
    userId: '1',
    createdAt: new Date('2024-01-15T09:00:00Z'),
    updatedAt: new Date('2024-01-15T14:30:00Z'),
  },
  {
    id: '2',
    title: 'Review code changes',
    description: 'Review pull requests and provide feedback to team members',
    priority: 'medium',
    status: 'pending',
    dueDate: new Date('2024-01-18T16:00:00Z'),
    estimatedDuration: 60,
    actualDuration: 20,
    aiGenerated: false,
    tags: ['work', 'code-review'],
    userId: '1',
    createdAt: new Date('2024-01-15T10:00:00Z'),
    updatedAt: new Date('2024-01-15T10:00:00Z'),
  },
  {
    id: '3',
    title: 'Plan weekly team meeting',
    description: 'Prepare agenda and materials for the weekly team sync meeting',
    priority: 'medium',
    status: 'completed',
    dueDate: new Date('2024-01-16T14:00:00Z'),
    estimatedDuration: 30,
    actualDuration: 25,
    aiGenerated: true,
    tags: ['meeting', 'planning'],
    userId: '1',
    createdAt: new Date('2024-01-14T15:00:00Z'),
    updatedAt: new Date('2024-01-16T14:30:00Z'),
  },
  {
    id: '4',
    title: 'Research new technologies',
    description: 'Research and evaluate new frontend frameworks for the project',
    priority: 'low',
    status: 'pending',
    dueDate: new Date('2024-01-25T17:00:00Z'),
    estimatedDuration: 180,
    actualDuration: 0,
    aiGenerated: false,
    tags: ['research', 'technology'],
    userId: '1',
    createdAt: new Date('2024-01-15T11:00:00Z'),
    updatedAt: new Date('2024-01-15T11:00:00Z'),
  },
  {
    id: '5',
    title: 'Update documentation',
    description: 'Update API documentation and user guides',
    priority: 'high',
    status: 'in_progress',
    dueDate: new Date('2024-01-19T17:00:00Z'),
    estimatedDuration: 90,
    actualDuration: 30,
    aiGenerated: false,
    tags: ['documentation', 'api'],
    userId: '1',
    createdAt: new Date('2024-01-15T13:00:00Z'),
    updatedAt: new Date('2024-01-15T16:00:00Z'),
  },
  {
    id: '6',
    title: 'Prepare presentation slides',
    description: 'Create presentation slides for the quarterly review meeting',
    priority: 'high',
    status: 'pending',
    dueDate: new Date('2024-01-22T10:00:00Z'),
    estimatedDuration: 120,
    actualDuration: 10,
    aiGenerated: true,
    tags: ['presentation', 'quarterly'],
    userId: '1',
    createdAt: new Date('2024-01-15T14:00:00Z'),
    updatedAt: new Date('2024-01-15T14:00:00Z'),
  },
  {
    id: '7',
    title: 'Overdue Task 1',
    description: 'This task is overdue and should appear in the overdue tab',
    priority: 'high',
    status: 'overdue',
    dueDate: new Date('2023-12-01T10:00:00Z'), // Overdue date
    estimatedDuration: 60,
    actualDuration: 0,
    aiGenerated: false,
    tags: ['overdue', 'urgent'],
    userId: '1',
    createdAt: new Date('2023-11-15T14:00:00Z'),
    updatedAt: new Date('2023-11-15T14:00:00Z'),
  },
  {
    id: '8',
    title: 'Overdue Task 2',
    description: 'Another overdue task that should be in the overdue tab',
    priority: 'medium',
    status: 'overdue',
    dueDate: new Date('2023-11-30T17:00:00Z'), // Overdue date
    estimatedDuration: 90,
    actualDuration: 45,
    aiGenerated: false,
    tags: ['overdue', 'work'],
    userId: '1',
    createdAt: new Date('2023-11-20T10:00:00Z'),
    updatedAt: new Date('2023-11-25T16:00:00Z'),
  },
];

// Mock Pomodoro Sessions
export const mockPomodoroSessions: PomodoroSession[] = [
  {
    id: '1',
    taskId: '1',
    userId: '1',
    startTime: new Date('2024-01-15T09:00:00Z'),
    endTime: new Date('2024-01-15T09:25:00Z'),
    duration: 25,
    type: 'work',
    completed: true,
  },
  {
    id: '2',
    taskId: '1',
    userId: '1',
    startTime: new Date('2024-01-15T09:30:00Z'),
    endTime: new Date('2024-01-15T09:35:00Z'),
    duration: 5,
    type: 'break',
    completed: true,
  },
  {
    id: '3',
    taskId: '5',
    userId: '1',
    startTime: new Date('2024-01-15T14:00:00Z'),
    endTime: new Date('2024-01-15T14:25:00Z'),
    duration: 25,
    type: 'work',
    completed: true,
  },
  {
    id: '4',
    taskId: '5',
    userId: '1',
    startTime: new Date('2024-01-15T14:30:00Z'),
    endTime: new Date('2024-01-15T14:35:00Z'),
    duration: 5,
    type: 'break',
    completed: true,
  },
];

// Mock Calendar Events
export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: '1',
    title: 'Team Meeting',
    description: 'Weekly team sync meeting',
    start: new Date('2024-01-16T10:00:00Z'),
    end: new Date('2024-01-16T11:00:00Z'),
    allDay: false,
    taskId: '3',
    userId: '1',
  },
  {
    id: '2',
    title: 'Project Review',
    description: 'Review project progress with stakeholders',
    start: new Date('2024-01-18T14:00:00Z'),
    end: new Date('2024-01-18T15:30:00Z'),
    allDay: false,
    taskId: '6',
    userId: '1',
  },
  {
    id: '3',
    title: 'Code Review Session',
    description: 'Review pull requests and provide feedback',
    start: new Date('2024-01-17T13:00:00Z'),
    end: new Date('2024-01-17T14:00:00Z'),
    allDay: false,
    taskId: '2',
    userId: '1',
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'Task Completed',
    message: 'Your task "Plan weekly team meeting" has been completed successfully!',
    type: 'success',
    read: false,
    taskId: '3',
    userId: '1',
    createdAt: new Date('2024-01-16T14:30:00Z'),
  },
  {
    id: '2',
    title: 'Due Date Reminder',
    message: 'Task "Complete project proposal" is due in 2 days',
    type: 'warning',
    read: false,
    taskId: '1',
    userId: '1',
    createdAt: new Date('2024-01-15T16:00:00Z'),
  },
  {
    id: '3',
    title: 'New AI Suggestion',
    message: 'AI has suggested 3 new tasks based on your current workload',
    type: 'info',
    read: true,
    taskId: undefined,
    userId: '1',
    createdAt: new Date('2024-01-15T12:00:00Z'),
  },
  {
    id: '4',
    title: 'Pomodoro Session Complete',
    message: 'Great job! You completed a 25-minute work session',
    type: 'success',
    read: true,
    taskId: '1',
    userId: '1',
    createdAt: new Date('2024-01-15T09:25:00Z'),
  },
];

// Mock AI Response
export const mockAIResponse = {
  tasks: [
    {
      title: 'Prepare quarterly report',
      description: 'Compile and analyze data for the quarterly performance report',
      priority: 'high' as const,
      dueDate: new Date('2024-01-25T17:00:00Z'),
      estimatedDuration: 180,
      tags: ['report', 'quarterly'],
    },
    {
      title: 'Update team documentation',
      description: 'Update team processes and procedures documentation',
      priority: 'medium' as const,
      dueDate: new Date('2024-01-23T17:00:00Z'),
      estimatedDuration: 90,
      tags: ['documentation', 'team'],
    },
  ],
  message: 'I\'ve analyzed your current workload and suggested 2 new tasks to help you stay organized.',
  confidence: 0.85,
};

// Mock Statistics
export const mockStats = {
  totalTasks: 6,
  completedTasks: 1,
  inProgressTasks: 2,
  pendingTasks: 3,
  totalPomodoroSessions: 4,
  totalWorkTime: 50, // minutes
  totalBreakTime: 10, // minutes
  averageSessionLength: 15, // minutes
  completedSessions: 4,
  incompleteSessions: 0,
  productivityScore: 85,
  weeklyProgress: 75,
}; 